src/WebApplication3/Controllers/GasesController.cs
using System;
using System.Linq;
using Microsoft.AspNet.Mvc;
using Newtonsoft.Json;
using WebApplication3.Models;
using WebApplication3.Services;
using Newtonsoft.Json.Serialization;
using Microsoft.AspNet.Authorization;

namespace WebApplication3.Controllers
{
  [Authorize(Roles = "administrator,upravnik")]
  public class GasesController : Controller
  {
    private readonly ApplicationDbContext _context;
    public static DateTime sd;
    public static DateTime se;


    public GasesController(ApplicationDbContext context)
    {
      _context = context;
    }

    // GET: Gases
    public IActionResult Index(DateTime startDate, DateTime endDate, string searchBtn)
    {
      var gases = from g in _context.Gases select g;

      gases = startDate > endDate
        ? gases.Where(g => g.datum == startDate)
        : gases.Where(g => g.datum >= startDate && g.datum <= endDate);


      return View(gases);
    }

    // GET: PARTIAL VIEW - Gases/_GasResultTable 
    public IActionResult GasResultTable(DateTime startDate, DateTime endDate, string searchBtn)
    {
      var gases = from g in _context.Gases select g;
      var result = "";

      gases = startDate > endDate
        ? gases.Where(g => g.datum == startDate)
        : gases.Where(g => g.datum >= startDate && g.datum <= endDate);

      if (!gases.Any() && !string.IsNullOrEmpty(searchBtn))
      {
        result = "Za izbran razpon ni vnosa";
      }

      ViewBag.Message = result;

      var sum = gases.AsEnumerable().Sum(p => p.proizvedena_kolicina);
      ViewBag.Summa = sum;

      return PartialView("_GasResultTable", gases);
    }

    // GET: Gases/Details/5
    public IActionResult Details(int? id)
    {
      if (id == null)
      {
        return HttpNotFound();
      }

      Gas gas = _context.Gases.Single(m => m.Id == id);
      if (gas == null)
      {
        return HttpNotFound();
      }

      return View(gas);
    }

    // GET: Gases/Create
    public IActionResult Create()
    {
      return View();
    }

    // POST: Gases/Create
    [HttpPost]
    [ValidateAntiForgeryToken]
    public IActionResult Create(Gas gas)
    {
      if (ModelState.IsValid)
      {
        _context.Gases.Add(gas);
        _context.SaveChanges();
        return RedirectToAction("Index");
      }
      return View(gas);
    }

    // GET: Gases/Edit/5
    public IActionResult Edit(int? id)
    {
      if (id == null)
      {
        return HttpNotFound();
      }

      Gas gas = _context.Gases.Single(m => m.Id == id);
      if (gas == null)
      {
        return HttpNotFound();
      }
      return View(gas);
    }

    // POST: Gases/Edit/5
    [HttpPost]
    [ValidateAntiForgeryToken]
    public IActionResult Edit(Gas gas)
    {
      if (ModelState.IsValid)
      {
        _context.Update(gas);
        _context.SaveChanges();
        return RedirectToAction("Index");
      }
      return View(gas);
    }

    // GET: Gases/Delete/5
    [ActionName("Delete")]
    public IActionResult Delete(int? id)
    {
      if (id == null)
      {
        return HttpNotFound();
      }

      Gas gas = _context.Gases.Single(m => m.Id == id);
      if (gas == null)
      {
        return HttpNotFound();
      }

      return View(gas);
    }

    // POST: Gases/Delete/5
    [HttpPost, ActionName("Delete")]
    [ValidateAntiForgeryToken]
    public IActionResult DeleteConfirmed(int id)
    {
      Gas gas = _context.Gases.Single(m => m.Id == id);
      _context.Gases.Remove(gas);
      _context.SaveChanges();
      return RedirectToAction("Index");
    }

    // GET: Gases/Graphs
    public IActionResult Graphs()
    {
      return View();
    }


    // GET: PARTIAL VIEW - Gases/_GasUtilization
    public IActionResult GasUtilization(DateTime startDate, DateTime endDate, string executeBtn)
    {
      sd = startDate;
      se = endDate;
      return PartialView("_GasUtilization");
    }


    public string GetAllGasesDateOutput()
    {
      var selection = (from g in _context.Gases select new { g.datum, g.proizvedena_kolicina }).ToArray();
      var list =
        selection.Select(g => new GasSelection { Datum = Conversion.getTime(g.datum), Proizvod = g.proizvedena_kolicina })
          .ToArray();

      object[,] dataFill = new object[list.Length, 2];
      for (int i = 0; i < list.Length; i++)
      {
        dataFill[i, 0] = list[i].Datum;
        dataFill[i, 1] = list[i].Proizvod;
      }

      string sArraySerializedIndented = JsonConvert.SerializeObject(dataFill, Formatting.Indented);
      return sArraySerializedIndented;
    }

    private class GasSelection
    {
      public long Datum { get; set; }
      public float Proizvod { get; set; }
    }

    public string GetUtilization(DateTime startDate, DateTime endDate, string executeBtn)
    {
      if (DateTime.Compare(sd, new DateTime(2013, 05, 06)) > 0)
      {
        startDate = sd;
        endDate = se;
      }
      //filtering
      //var selection = (from g in _context.Gases select new { g.ura_zacetnega_vpisa, g.ura_koncnega_vpisa }).ToArray();
      //if (DateTime.Compare(startDate, new DateTime(2013, 05, 07)) < 0)
      //{
      //  startDate = new DateTime(2013, 05, 07);
      //  endDate = DateTime.Now;
      //}

      var gases = from g in _context.Gases select g;
      var result = "";

      gases = startDate > endDate
        ? gases.Where(g => g.datum == startDate)
        : gases.Where(g => g.datum >= startDate && g.datum <= endDate);

      if (!gases.Any() && !string.IsNullOrEmpty(executeBtn))
      {
        result = "Za izbran razpon ni vnosa";
      }

      ViewBag.Message = result;

      var selection = gases.AsEnumerable().Select(g => new { g.ura_zacetnega_vpisa, g.ura_koncnega_vpisa }).ToArray();

      // calculations
      var count = selection.Count();

      var totalTimeSpan = new TimeSpan[count];
      var totalMin = 0f;

      for (int i = 0; i < count; i++)
      {
        totalTimeSpan[i] = selection[i].ura_koncnega_vpisa.Subtract(selection[i].ura_zacetnega_vpisa);
        totalMin += (float)totalTimeSpan[i].TotalMinutes;
      }

      var totalPercentage = (totalMin / (count * 1440)) * 100;

      //assigning to make ready for json serialization
      object[] obj = new object[2];

      GasUtil gas = new GasUtil();
      gas.Name = "V uporabi";
      gas.Y = totalPercentage;

      GasUtil gasN = new GasUtil();
      gasN.Name = "V mirovanju";
      gasN.Y = 100f - gas.Y;

      obj[0] = gas;
      obj[1] = gasN;

      string sArrIndented = JsonConvert.SerializeObject(obj, Formatting.Indented, new JsonSerializerSettings { ContractResolver = new CamelCasePropertyNamesContractResolver() });

      return sArrIndented;
    }

    private class GasUtil
    {
      public string Name { get; set; }
      public float Y { get; set; }
    }

  }
}

src/WebApplication3/Views/Gases/Details.cshtml
@model WebApplication3.Models.Gas

@{
    ViewData["Title"] = "Details";
}

<h2>Details</h2>

<div>
    <h4>Gas</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.datum)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.datum)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.koncno_stanje)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.koncno_stanje)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.koncno_stanje_cela)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.koncno_stanje_cela)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.koncno_stanje_cifra)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.koncno_stanje_cifra)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.proizvedena_kolicina)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.proizvedena_kolicina)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.ura_koncnega_vpisa)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.ura_koncnega_vpisa)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.ura_zacetnega_vpisa)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.ura_zacetnega_vpisa)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.zacetno_stanje)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.zacetno_stanje)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.zacetno_stanje_cela)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.zacetno_stanje_cela)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.zacetno_stanje_cifra)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.zacetno_stanje_cifra)
        </dd>
    </dl>
</div>
<p>
    <a asp-action="Edit" asp-route-id="@Model.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</p>

src/WebApplication3/Views/Gases/Graphs.cshtml
@{
  ViewData["Title"] = "Grafi";
}

<article id="contain" class="row body-content article-content"></article>

<article class="row body-content article-content">
  <div class="col-lg-offset-2 col-lg-2 col-md-6">
    <h3>Graf uporabe</h3>
    @using (Html.BeginForm("GasUtilization", "Gases", FormMethod.Get, new
    {
      id = "executeBtn",
      data_ajax = "true",
      data_ajax_method = "GET",
      data_ajax_mode = "replace",
      data_ajax_update = "#contain1",
      @class = "form-horizontal body-content"
    }))
    {<div class="form-group form-inline">
      <label for="startDate" class="control-label">Od</label>
      <input type="date" id="startDate" name="StartDate" placeholder="dd.mm.llll" class="form-control" required>
    </div>
    <div class="form-group form-inline">
      <label for="endDate" class="control-label">Do</label>
      <input type="date" id="endDate" name="EndDate" placeholder="dd.mm.llll" class="form-control">
    </div>
    <div class="form-group">
      <input name="executeBtn" type="submit" value="Poizvedi" class="btn btn-default" />
    </div>
    }
  </div>

  <div id="contain1" class="col-lg-8 col-md-6">
    @section ScriptsPartial {
      @{
        await Html.RenderPartialAsync("_GasUtilization");
      }
    }
  </div>
</article>

@section Scripts {
  <script src="~/lib/jquery-ajax-unobtrusive/jquery.unobtrusive-ajax.js"></script>
  <script src="~/lib/highstock/highstock.js"></script>
  <script src="~/lib/highstock/modules/exporting.js"></script>
  <script src="~/js/graphProduction.js"></script>
  @*<script src="~/js/graphUtilization.js"></script>*@
}

src/WebApplication3/Views/Gases/Index.cshtml
@model IEnumerable<WebApplication3.Models.Gas>

@{
  ViewData["Title"] = "Poizvedbe";
}

<article class="row body-content">
  <div class="col-sm-3">
    <h3>Tabela vnosov</h3>
    @using (Html.BeginForm("GasResultTable", "Gases", FormMethod.Get, new
    {
      id = "searchBtn",
      data_ajax = "true",
      data_ajax_method = "GET",
      data_ajax_mode = "replace",
      data_ajax_update = "#gasTableContainer",
      @class = "form-horizontal body-content"
    }))
    {
      <div class="form-group form-inline">
        <label for="startDate" class="control-label">Od</label>
        <input type="date" id="startDate" name="StartDate" placeholder="dd.mm.llll" class="form-control" required>
      </div>
      <div class="form-group form-inline">
        <label for="endDate" class="control-label">Do</label>
        <input type="date" id="endDate" name="EndDate" placeholder="dd.mm.llll" class="form-control">
      </div>
      <div class="form-group">
        <input name="searchBtn" type="submit" value="I&#353;&#269;i" class="btn btn-default" />
      </div>
    }
  </div>

  <div id="gasTableContainer" class="article-content col-sm-9">
    @{
      await Html.RenderPartialAsync("_GasResultTable");
    }
  </div>
</article>

@section Scripts {
  <script src="~/lib/jquery-ajax-unobtrusive/jquery.unobtrusive-ajax.js"></script>
}

src/WebApplication3/Views/Gases/_GasResultTable.cshtml
@model IEnumerable<WebApplication3.Models.Gas>
@{
  if (ViewBag.Message != null)
  {
    <div class="form-group text-danger">
      <span>@ViewBag.Message</span>
    </div>
  }
  <div class="form-group">
    <label class="control-label">SUMMA</label>
    <span>@ViewBag.Summa</span>
  </div>
}

<table class="table table-responsive table-striped">
  <tr>
    <th>
      @Html.DisplayNameFor(model => model.datum)
    </th>
    <th>
      @Html.DisplayNameFor(model => model.proizvedena_kolicina)
    </th>
    <th>
      @Html.DisplayNameFor(model => model.ura_zacetnega_vpisa)
    </th>
    <th>
      @Html.DisplayNameFor(model => model.ura_koncnega_vpisa)
    </th>
  </tr>

  @foreach (var item in Model)
  {
    <tr>
      <td>
        @Html.DisplayFor(modelItem => item.datum)
      </td>
      <td>
        @Html.DisplayFor(modelItem => item.proizvedena_kolicina)
      </td>
      <td>
        @Html.DisplayFor(modelItem => item.ura_zacetnega_vpisa)
      </td>
      <td>
        @Html.DisplayFor(modelItem => item.ura_koncnega_vpisa)
      </td>
    </tr>
  }
</table>

src/WebApplication3/Views/Gases/_GasUtilization.cshtml
@{
  if (ViewBag.Message != null)
  {
    @ViewBag.Message
  }
}
<span id="contain2">
  <script src="~/js/graphutilization.js"></script>
</span>